#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2024 Stanford University
#
# SPDX-License-Identifier: MIT
#

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play (Alpha)"
  lane :alpha do
    gradle(
      task: "clean assembleRelease",
      properties: {
        "android.injected.version.code" => 100,
        "android.injected.version.name" => "1.0.0",
        "android.injected.signing.store.file" => "keystore.jks",
        "android.injected.signing.store.password" => ENV['KEY_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
      }
    )
    upload_to_play_store(
      track: 'alpha',
      json_key_data: ENV['FASTLANE_SERVICE_ACCOUNT_JSON_KEY']
    )
  end
end
