name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detekt:
    name: Run detekt
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: detekt
        uses: alaegin/Detekt-Action@v1.23.6
        with:
          reviewdog_reporter: github-pr-review
          github_token: ${{ secrets.github_token }}
          detekt_config: config/detekt-config.yml

  check:
    needs: detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and Test with Gradle
        run: chmod +x ./gradlew && ./gradlew build test
