name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detekt:
    name: Detekt review
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: detekt-pr-check
        uses: alaegin/Detekt-Action@v1.23.6
        with:
          reviewdog_reporter: github-pr-check
          github_token: ${{ secrets.github_token }}
          detekt_config: internal/detekt-config.yml
      - name: detekt-evaluate
        if: always()  # Ensure this runs even if the previous step fails
        run: |
          if grep -qE "(Analysis failed|conclusion=failure)" <(echo "$GITHUB_JOB_LOG"); then
            echo "Detekt analysis failed" >&2
            exit 1
          fi

  check:
    name: Build and test
    needs: [detekt]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Change permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test
