#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2024 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Release

on:
  release:
    types: [published]

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  build-and-test:
    name: Build and Test
    uses: ./.github/workflows/deployment.yml
    permissions:
      contents: read
      checks: write
      actions: read
      security-events: write
    secrets: inherit
    with:
      environment: production
      version: ${{ github.event.release.tag_name }}